name: Build Linux

on:
  workflow_call:
    inputs:
      official:
        required: true
        type: boolean

jobs:
  build:
    runs-on: [self-hosted, pure1build]
    container:
      image: artifactory.pstg-inf.net:443/dockerhub-registry-1/golang:1.21-bullseye
    permissions:
      contents: read
      actions: read
    env:
      DEFAULT_HOST: "keymaster.sec.cloud-support.purestorage.com"
      VERSION_FLAVOUR: "pure"
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Disable git safe directory warnings
      run: git config --global --add safe.directory '*'

    - run: |
        dpkg --add-architecture arm64
        apt-get update
        apt-get install -y gcc rpm alien rsync pkg-config libudev-dev build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libudev-dev:arm64

    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"

    - run: |
        env GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc make build
        cp bin/keymaster bin/keymaster-arm64
        env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 make build rpm
        cp bin/keymaster bin/keymaster-amd64

    - uses: actions/upload-artifact@v4
      with:
        name: keymaster-linux
        path: |
          bin/keymaster
          bin/keymaster-arm64
          bin/keymaster-amd64
