name: Build Windows

on:
  workflow_call:
    inputs:
      official:
        required: true
        type: boolean

jobs:
  build:
    runs-on: [self-hosted, Windows]
    permissions:
      contents: read
      actions: read
    env:
      DEFAULT_HOST: "keymaster.sec.cloud-support.purestorage.com"
      VERSION_FLAVOUR: "pure"
    steps:
    - uses: actions/setup-go@v5
      if: false  # preinstalled go is used atm.
      with:
        go-version: "1.22.x"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Disable git safe directory warnings
      run: git config --global --add safe.directory '*'

    - name: Build keymaster amd64
      run: |
        & 'C:\git-sdk-64\msys2_shell.cmd' -mingw64 -no-start -here -defterm -c 'make client-test build-client;'
      shell: powershell
      env:
        GOOS: windows
        GOARCH: amd64

    - uses: actions/upload-artifact@v4
      with:
        name: keymaster-windows
        path: |
          bin/keymaster.exe
