name: Publish to Artifactory

on:
  workflow_call:
    inputs:
      official:
        required: true
        type: boolean
      target:
        required: true
        type: string

jobs:
  publish:
    runs-on: [ self-hosted, pure1build ]
    container:
      image: artifactory.pstg-inf.net:443/pstg-docker-official/pure1/pure1build-images/go-1-21:0.1.0
      volumes:
        - /root/.purelogin/spinnaker:/root/.purelogin/spinnaker
        - ${{ inputs.official && '/root/.purelogin/env-official:/root/.purelogin/env-official' || '/root/.purelogin/env-sandbox:/root/.purelogin/env-sandbox' }}

    permissions:
      contents: read
      actions: read

    env:
      CI_PROD: ${{ inputs.official }}
      VERSION_FLAVOUR: "pure"
      ARTIFACTORY_BASE_URL: "https://artifactory.pstg-inf.net/artifactory"
      ARTIFACTORY_URL: "https://artifactory.pstg-inf.net/artifactory/${{ inputs.official && 'pstg-maven-official' || 'pstg-maven-sandbox' }}/com/purestorage/keymaster"

    steps:
      - name: Load env secrets
        uses: pure-pure1/pure1build-github-actions/actions/load-env-secrets@v1.1.1
        with:
          secrets_file: ${{ inputs.official && '/root/.purelogin/env-official/values.txt' || '/root/.purelogin/env-sandbox/values.txt' }}

      - run: printenv | cut -d '=' -f1

      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: false

      - name: Postprocess artifact
        run: |
          ls -lasR artifacts/ || true
          cd artifacts/keymaster-${{ inputs.target }}
          zip -r ../keymaster-${{ inputs.target }}.zip .
          ls -lasR . || true

      - name: Publish to artifactory
        id: prepare
        uses: actions/github-script@v7
        with:
          script: |
            const platform = "${{ inputs.target }}";
            const isMainBranch = ${{ inputs.official }};
            
            const script = require(process.env.GITHUB_WORKSPACE + '/.github/workflows/_publish.js');
            await script({platform, isMainBranch, github, context, core, fetch})
