on:
  pull_request:
  push:
    branches: [ main, master, 'main-*', 'master-*', rc, 'rc-*' ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.*"
  merge_group:

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

name: Build Linux
jobs:
  build:
    runs-on: [self-hosted, pure1build]
    container:
      image: artifactory.pstg-inf.net:443/dockerhub-registry-1/golang:1.21-bullseye
    permissions:
      contents: read
      actions: read
    env:
      DEFAULT_HOST: "keymaster.sec.cloud-support.purestorage.com"
      EXTRA_BUILD_FLAGS: "-buildvcs=false "
    steps:

    - uses: actions/checkout@v4

    - run: |
        apt-get update
        apt-get install -y gcc rpm alien rsync pkg-config libudev-dev build-essential

    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"

    - run: make build

    - run: make rpm

    - uses: actions/upload-artifact@v4
      with:
        name: keymaster-linux
        path: bin/keymaster

  publish:
    needs:
      - build
    uses: ./.github/workflows/_publish.yml
    with:
      official: ${{ github.ref == 'refs/heads/main' }}
      target: 'linux'
