name: Publish to Sandbox
on:
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/_build-all.yml
    with:
      official: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
