on:
  pull_request:
  push:
    branches: [ main, master, 'main-*', 'master-*', rc, 'rc-*' ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.*"
  merge_group:

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

name: Test
jobs:
  test:
    runs-on: [self-hosted, pure1build]
    container:
      image: artifactory.pstg-inf.net:443/pstg-docker-official/pure1/pure1build-images/go-1-21:0.1.0
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"
    - uses: actions/checkout@v4
    - run: make test
